name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up environment
  #       run: |
  #         mv .env.test .env

  #     - name: Install dependencies
  #       run: |
  #         npm install -g bun
  #         bun install

  #     - name: lint
  #       run: |
  #         bun lint
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          mv .env.test .env

      - name: Install dependencies
        run: |
          npm install -g bun
          bun install

      - name: check
        run: |
          bun check
