name: Test Drizzle Migrations

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-migrations:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ocamp
        options: >-
          --health-cmd="pg_isready -U admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "DATABASE_URL=postgres://admin:password@localhost:5432/ocamp" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          npm install -g bun
          bun install

      - name: Run Drizzle migrations
        run: |
          npx drizzle-kit migrate:latest
          # Adjust the command based on how you run Drizzle migrations

      # - name: Run tests
      #   run: |
      #     bun test
